### ISSUE TITLE
Possible incorrect use of subbytes

### ISSUE THREAD

**Issue by bmitc** [Apress/introducing-blockchain-with-lisp#1]
Hello! Thank you for this book. I am using it to learn blockchain concepts.

In Section 3.2.3 (Hashcash Algorithm), I believe there may be a bug in the `mined-block?` implementation or a typo in the text. This is the function definition:

https://github.com/Apress/introducing-blockchain-with-lisp/blob/fab4dd8d999bab089927307e17a743f26aa827ee/racket-coin-master/src/block.rkt#L24-L28

In the book, there is the line (on page 77, Section 3.2.3):

> Thus, given a random hash, we consider it to be valid if its first two (in this case, per `difficulty`) bytes match the `target`.

However, the use of [`subbtyes`](https://docs.racket-lang.org/reference/bytestrings.html#%28def._%28%28quote._~23~25kernel%29._subbytes%29%29) only selects a single byte when `difficulty` is 2:

```racket
(subbytes (hex-string->bytes target) 1 difficulty)
```

This only selects the second byte returned by `(hex-string->bytes target)` when `difficulty` is 2. For example:

```racket
(subbytes #"asdf" 1 2)
```
returns `#"s"`, such that only a single byte is returned.

I think the 1 in the `mined-block?` definition should be 0. For example, `(subbytes #"asdf" 0 2)` returns `#"as"`.

**Comment by objecthub** [comment]
I stumbled across the very same issue. I'm pretty sure that this should read

```
(equal? (subbytes (hex-string->bytes hash) 0 difficulty) 
        (subbytes (hex-string->bytes target) 0 difficulty))
```

**Comment by bmitc** [comment]
I'm closing this issue due to zero activity on this repository by the author and publisher. Other readers can still find this in the closed issues and via web searches.
